# Site settings
title: Brian Zhang
email: brianhszhang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Awesome sauce!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Brian Zhang
email: brianhszhang@gmail.com
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
